name: Tweet Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '0 4 * * *'   # 04:00 UTC
    - cron: '0 8 * * *'   # 08:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 16 * * *'  # 16:00 UTC
    - cron: '0 20 * * *'  # 20:00 UTC

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Repository ophalen
        uses: actions/checkout@v3

      - name: Python installeren
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Afhankelijkheden installeren
        run: pip install -r requirements.txt

      - name: NLTK data downloaden
        run: |
          python -m nltk.downloader punkt stopwords

      - name: Tweet plaatsen
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python tweet_bot.py
